name: "user-web"
serverPort: 8082

user-srv:
  targetHost: "192.168.2.113"
  targetPort: 8088

jwt:
  signingKey: "K>Tc.Y+21J!R*v~P%FM==J@xY]i:?sMJ"

redis:
  host: "localhost"
  port: 26379
  db: 1
  expirationTime: "5m"

captcha:
  enableCaptcha: true
  # type audio,string,math,chinese,
  type: "math"
  sourceChinese: "的一了是不在的人有我他这中大为上个国我们要和到也你就得着说们国人她"

consul:
  host: "127.0.0.1"
  port: 8500
  srvName: "user-srv"