host: "192.168.2.150"
port: 8848
scheme: "http"
namespace: "5dd8ea5d-850c-447c-8653-de0dda05d906"
dataId: "order_api"
group: "dev"

#server:
#  host: "192.168.2.150"
#  name: "goods_api"
#  port: 8083
#  timezone: "Asia/Shanghai"
#jwt:
#  signingKey: "sHAY*g=N,0eN}+b1FYo+c]!CwAw^4kVm"
#consul:
#  host: "192.168.2.150"
#  port: 8500
#  target: "goods_srv"
#  targetServerName: "goods_srv"

