host: "192.168.2.150"
port: 8848
scheme: "http"
namespace: "c5ed7cca-21ca-43dd-81ac-6a5c4689c993"
dataId: "order_srv"
group: "dev"

#server:
#  host: "192.168.2.150"
#  name: "goods_api"
#  port: 8083
#  timezone: "Asia/Shanghai"
#jwt:
#  signingKey: "sHAY*g=N,0eN}+b1FYo+c]!CwAw^4kVm"
#consul:
#  host: "192.168.2.150"
#  port: 8500
#  target: "goods_srv"
#  targetServerName: "goods_srv"

